travis:
  secure:
    BINSTAR_TOKEN: rvUnZxP1Bb65N6APAfYRcQxvwznKMwWK/SqyqoZRQmTxlme4nh+p6sISF0jxiDCAeL2TbZ3uCD+uWS8pqJ+CC24XQsscX0j5ks896RbwufBII/fe9sPRSjgBxelVenzS5rasKl7VOZPA9/bzZeE1PbgZjXWRpcGbE7R15TU3nBGAnPbtHxGJHehoGMFojDZgiF5+UvQGfRTxS0Lm3++CGR4wDSZr2gLLCBaMd+nk/24/EUNlg9GQfSdcy4sYYH5XijlbZqaZStmCoYNm0IL0ctZy+m7vOpHHbbSFokNuylEnedpYK7zJ0Qyn0f0iEwZShsnwB/ZKJI758YCSGsavA0V+E9QMenqctifF6mNBM/1oB/baLoJrYBdadFDSxWdHNP6sGsAz+Wr4TkD8OJMQnEhvtuSjlM7SrCwnMEbEqgqt6mhUNpf9BtFrKNGylANHK8Px+MLIb2S//XYcss8utVgEtcMKkqL51vyKUf4PogzuuINrkHV97z4tEpsmL+8Ad1wy9abmXSiORlW9CfoZD2oKQq/nWt6W5rxP5+HhAZbhMmUHS9TxgZOWBXITidplXi8Q+HqVx2Dh4G88p3WVpP0PsWx2OIJz0RlxvdpdXPItP78tLzOw18mNN9he+Z089T/vkgEJKJZQfQkWfQTHyGyXNrCEphrJErnIDjfec3Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
