travis:
  secure:
    BINSTAR_TOKEN: KfCyRidJO1O2RUXiVD6mMpu0YTXv0+cPJJJYexxDPY6A45aCC/s3NQAAR3jQv7JmRAzjdPCKmUgvQaSo1wwXtFuJWH9tcUsrtFD2m6QWkMmKeQ41fAubTEabd7HFlPLI+Utyk1DBW4ZqdEim3X7vEJpZRAFvxSvNAi8YSIKWGBpdFlLiKJFW+eDZfAmWv0MBqEadnZ9KRW+11yzsgoRJUBp6hdgSxNc1CZ6KZCHawzKStY1aI45zK8Fx3RnKRrvSKXd47D/Fbt1XEBrKMuntfWYUUzRvAdEkrPuI/AVkVwntua14wkmzX1otnYodURke3h1GkUHfZtLEzZ9SY77A1h3JZrMX/JqnzMgjgf013XL8nfcrJYEHtr5YpRj7bLV+bIQGV66LnLItpvuP4Pf0yFg61E4v4sBHp0lprpo/4+75WjjneZ9z78+VusrVrAKYgfEx846qzTs/CQQJ+bjtG9qvgUc4ON6Gni5T/voCsMPm0DHC9FrhP51LVVWUzLHcVR8mXDzdLsV2NZIFTxplLGf84eLa6gR/RsdKoMUfJfNNTUO0O0fXiHpWdiB43t3+VEQrPLtY6XrzjqCYCA3wgyL098O+ivyM03TFVBeY7PmDFoTC6MDiky0emAJbXVu8XJg2nb2qULoi7RGGZhQqdcbLdP/oA0+nhk5VgUI6wuc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
